server {
    listen       8080;
    listen  [::]:8080;
    server_name  localhost;

    # 確保日誌直接輸出到 stdout/stderr，方便在 GCP 控制台查看
    access_log  /dev/stdout;
    error_log   /dev/stderr notice;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        # 支援漂亮網址
        try_files $uri $uri.html $uri/ /index.html;
    }

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }

    # 關閉 sendfile 以避免在虛擬化檔案系統中的快取問題
    sendfile off;
}
